import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TheApp from "./TheApp";
import { AudioPlayerProvider } from "@/context/AudioPlayerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="select-none bg-black">
            <body className={inter.className}>
                <AudioPlayerProvider>
                    <TheApp>{children}</TheApp>
                </AudioPlayerProvider>
            </body>
        </html>
    );
}
